apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkSFZ5YVhOMGFXZHZjanBuYUhCZlUyNDFTV3RDU1RsUmJGRmlWa05ZZGtaNWFuWjBVMjFZYXpSNGRqbEtNM1p3YTB4USIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFXZHZjblIxY21semREcERhR2x3YVZwYVpISnBZekkzTVRneU9BPT0iCgkJfSwKCQkicmVnaXN0cnkueWFuZGV4LWFjYWRlbXkucnUiOiB7CgkJCSJhdXRoIjogImFXZHZjaTF0YVd0b1pYbGphR1YyTWpBeE5EcG5lbkJEYm1GTmRDMUthbEZGZVVwTVJqY3lMUT09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
